### ISSUE TITLE
try mxnet?

### ISSUE THREAD

**Issue by Primus-zhao** [commaai/research#13]
Hello George, 

Appreciate that you can share your code. Just got one suggestion, hope it's useful. I know that Keras is quite good and simple, but tensorflow is slow compared with other tools such as mxnet and caffe, even slower than theano. Recently i'm converting to mxnet and found that it can save GPU memory,  keep high speed as well as support distributed computation(which i thought would be a trend in future self-driving car), besides, its net-built method is quite like Keras. 
I'm rewriting your network with mxnet now and will finish it in a couple of weeks. Will send you the speed and memory comparison results after that.

**Comment by geohot** [comment]
Internally we have some stuff in mxnet. Nice library, almost 2x speedup for training.

These are research models, not the models we are currently using the drive the car.

**Comment by Primus-zhao** [comment]
Good! Can't wait to see your products! In fact i'm also a self-driving guy in automotive industry, unfortunately can't convince my boss that ML is the future of self-driving. All of them are fond of stupid rule based methods. Hope your prod can punch them in the face!
