### ISSUE TITLE
Did you use two cameras to capture the pictures or videos ?

### ISSUE THREAD

**Issue by wizardbyron** [commaai/research#17]
Two cameras will help you to build an 3d-vector space to help you software get more precise data.

Think about two eyes vs one eye when you are driving.

I think it's little bit waste time to ML one eye data.

PS: do you have a mail list or google group about research?

**Comment by geohot** [comment]
Structure from motion. You don't really need two cameras.

**Comment by VanushVaswani** [comment]
@wizardbyron  Check out this for an example of what you can do with a single camera!

https://www.youtube.com/watch?v=C6-xwSOOdqQ

**Comment by EderSantana** [comment]
> I think it's little bit waste time to ML one eye data.

this is really wrong. the most productive effort in ML for computer vision nowadays are based on single camera vision. 
plus, one-eyed driver discrimination is not really politically correct

**Comment by EderSantana** [comment]
@VanushVaswani thanks for that paper. it looks interesting
