### ISSUE TITLE
from utils import load, save

### ISSUE THREAD

**Issue by cakeinspace** [commaai/research#33]
i know this is a stupid doubt but i googled this and couldnt find an answer, line 20 in autoencoder.py has 
from utils import load, save. I am getting an error in this line.
I tried conda install utils, pip install utils but none of these seem to work. 
How can i install this utils package.
Thanks

**Comment by amrit110** [comment]
utils refers to utils.py in models

**Comment by cakeinspace** [comment]
oh yeah I saw that later on thanks
