### ISSUE TITLE
the code cannot move forward

### ISSUE THREAD

**Issue by pandamax** [commaai/research#45]
INFO:__main__:server started
INFO:dask_generator:Loading 9 hdf5 buckets.
x 52722 | t 263583 | f 52722
x 58993 | t 294919 | f 58993
x 19731 | t 98719 | f 19731
x 56166 | t 280785 | f 56166
x 25865 | t 129344 | f 25865
x 85296 | t 426596 | f 85296
x 78463 | t 392182 | f 78463
x 30538 | t 152650 | f 30538
x 51691 | t 258571 | f 51691
training on 437158/459465 examples
INFO:dask_generator:camera files 9
843.83 ms
X (64, 1, 3, 160, 320)
angle (64, 1, 1)
speed (64, 1, 1)

???

**Comment by ahmedyahia3393** [comment]
The code will move forward when you execute the next file (training file)
