### ISSUE TITLE
about How to get the predicted steer given a new image input

### ISSUE THREAD

**Issue by ztl2004** [commaai/research#7]
hi, I've read the train_steer_model.py, but I didn't find the relation between that output shape and steer, could you please explain? As far as I see, it still ouput some kind of image, thanks!

model.add(Lambda(lambda x: x/127.5 - 1.,
            input_shape=(ch, row, col),
            output_shape=(ch, row, col)))

**Comment by EderSantana** [comment]
That is just the first layer of the model. It converts the input from uint8 to float between -1 and 1

**Comment by ztl2004** [comment]
thanks for this quick and accurate answer
