### ISSUE TITLE
Is the model in Comma 3 open sourced?

### ISSUE THREAD

**Issue by Manojbhat09** [commaai/research#73]
I was looking for the model and training pipeline from Herald's talk, are they open sourced, where can I find them?
https://www.youtube.com/watch?v=7u9sdenbI5M

**Comment by Torch-HXM** [comment]
No.It's NVIDIA's PilotNet.

**Comment by geohot** [comment]
The weights and architecture are open: https://github.com/commaai/openpilot/blob/master/selfdrive/modeld/models/supercombo.onnx
